services:
  api_service:
    build:
      context: .
      dockerfile: ./backend/api_service/Dockerfile
    container_name: api_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - prediction_service
      - clustering_service

  prediction_service:
    build:
      context: .
      dockerfile: ./backend/prediction_service/Dockerfile
    container_name: prediction_service
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - app_network

  clustering_service:
    build:
      context: .
      dockerfile: ./backend/clustering_service/Dockerfile
    container_name: clustering_service
    ports:
      - "8002:8002"
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
