services:
  api_service:
    build:
      context: .
      dockerfile: ./backend/api_service/Dockerfile
    container_name: forecast_api
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - prediction_service

  prediction_service:
    build:
      context: .
      dockerfile: ./backend/prediction_service/Dockerfile
    container_name: forecast
    ports:
      - "8001:8001"
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
